import sys
sys.path.insert(0, "/home/user/workspace/legal-work/target/scripts/_tmp_gen")
from docx_helper import new_document, add_title, add_h2, add_h3, add_p, add_letterhead, add_table, add_formathinweis, save

BASE = "/home/user/workspace/legal-work/target/testakten/unfallversicherung-arbeitsunfall-lagerleiter-sturz-trier/"
BG = ["Berufsgenossenschaft Handel und Warenlogistik", "Bezirksverwaltung Trier", "Loebstrasse 22, 54292 Trier", "Aktenzeichen: BGHW-2026-350118-MOELLER"]

# 20 - Zeugenprotokolle mind 2 mit Anschriften
doc = new_document()
add_title(doc, "Zeugenprotokolle mit Anschriften")
add_letterhead(doc, BG)
add_h2(doc, "1. Zeugenprotokoll Bastian Kopp")
add_p(doc, "Bastian Kopp, geboren 04.02.1988, wohnhaft Zurmaiener Strasse 88, 54292 Trier, Staplerfahrer bei MoselLogistik GmbH seit 2019. Vernehmung am 20.04.2026 durch die BG-Aussendienstmitarbeiterin Frau Corinna Radtke.")
add_p(doc, "Aussage: 'Ich habe Herrn Moeller gegen 6:38 Uhr auf dem Weg zu Rampe 4 gesehen, mit einem Brecheisen in der Hand. Ich bin dann mit Palette 112 in Halle C weitergefahren. Um etwa 6:42 Uhr habe ich einen lauten Schlag gehoert, der von Rampe 4 kam. Als ich hingefahren bin, sass Herr Moeller auf dem Boden und hielt sich die Schulter. Er hat gesagt, die Bruecke haette nachgegeben.'")
add_h2(doc, "2. Zeugenprotokoll Sandra Lehnert")
add_p(doc, "Sandra Lehnert, geboren 17.11.1979, wohnhaft Kaiserstrasse 41, 54290 Trier, Disponentin bei MoselLogistik GmbH seit 2013. Vernehmung am 20.04.2026, ebenfalls durch Frau Radtke.")
add_p(doc, "Aussage: 'Um kurz vor 6:40 Uhr kam ueber Funk die Meldung: Rampe 4 klemmt wieder. Ich kann nicht mehr sagen, wer das gefunkt hat, ich glaube aber, es war entweder Herr Moeller selbst oder der Staplerfahrer Kopp. Im Wartungsbuch fuer Maerz stehen mindestens drei Eintraege zur schwergaengigen Bruecke an Rampe 4. Ein Techniker war fuer den 8. April angekuendigt.'")
add_h2(doc, "3. Ergaenzende dritte Auskunftsperson")
add_p(doc, "Rampenwart Herbert Nauheim, geboren 22.06.1965, wohnhaft Weberbach 3, 54290 Trier, gibt schriftlich an, dass er die Ueberladebruecke an Rampe 4 zuletzt am 30.03.2026 provisorisch nachgefettet habe, weil das Ersatzteil fuer den Hydraulikzylinder noch nicht eingetroffen sei. Er habe die Betriebsleitung mehrfach muendlich auf den Zustand hingewiesen.")
add_h2(doc, "4. Wuerdigung durch die Kanzlei")
add_p(doc, "Alle drei Aussagen stuetzen unabhaengig voneinander, dass die Ueberladebruecke an Rampe 4 im relevanten Zeitraum technisch auffaellig war und dass Herr Moeller sich unmittelbar nach dem Sturz spontan und uebereinstimmend zum Hergang geaeussert hat.")
add_formathinweis(doc)
save(doc, BASE + "20_zeugenprotokolle_mit_anschriften.docx")

# 21 - BG-Aktenauszug Paragraf 25 SGB X
doc = new_document()
add_title(doc, "Antrag auf Akteneinsicht nach Paragraf 25 SGB X")
add_letterhead(doc, ["Kanzlei Lindenhof und Partner mbB", "Domfreihof 6, 54290 Trier"])
add_h2(doc, "1. Antrag")
add_p(doc, "Namens und im Auftrag des Herrn Karsten Moeller wird Akteneinsicht in die vollstaendige Verwaltungsakte zum Vorgang BGHW-2026-350118-MOELLER beantragt, einschliesslich aller internen Vermerke, des Wartungsbuchs Rampe 4, des Kameraausfallprotokolls und der Betriebspruefungsunterlagen, soweit diese beigezogen wurden.")
add_h2(doc, "2. Rechtsgrundlage")
add_p(doc, "Der Antrag stuetzt sich auf Paragraf 25 SGB X. Als Beteiligter im Sinne von Paragraf 12 SGB X hat der Mandant ein Recht auf Einsicht in die ihn betreffenden Akten, soweit deren Kenntnis zur Geltendmachung seiner rechtlichen Interessen erforderlich ist.")
add_h2(doc, "3. Antwort der Berufsgenossenschaft")
add_p(doc, "Mit Schreiben vom 06.05.2026 gewaehrte die Berufsgenossenschaft Akteneinsicht in Form einer elektronischen Aktenkopie. Das uebersandte Wartungsbuch enthielt lediglich die Eintraege ab Januar 2026; ein handschriftlicher Vermerk der Betriebsleiterin vom 05.04.2026 zur Schwergaengigkeit der Rampe war nicht Bestandteil der uebersandten Unterlagen.")
add_h2(doc, "4. Nachforderung")
add_p(doc, "Mit weiterem Schreiben vom 12.05.2026 wurde die vollstaendige interne Korrespondenz der MoselLogistik GmbH mit der Berufsgenossenschaft angefordert, insbesondere die E-Mail der Betriebsleiterin Jana Probst vom 05.04.2026.")
add_formathinweis(doc)
save(doc, BASE + "21_bg_aktenauszug_akteneinsicht_paragraf25.docx")

# 22 - BG-Anhoerung vor Ablehnung
doc = new_document()
add_title(doc, "Anhoerungsschreiben der Berufsgenossenschaft")
add_letterhead(doc, BG)
add_p(doc, "Datum: 28.05.2026")
add_h2(doc, "1. Beabsichtigte Entscheidung")
add_p(doc, "Die Berufsgenossenschaft teilt mit, dass nach Auswertung der D-Arzt-Berichte, des MRT-Befundes und der betrieblichen Unfallanzeige beabsichtigt ist, die Anerkennung eines Arbeitsunfalls abzulehnen, da ein von aussen auf den Koerper einwirkendes Ereignis nicht im Sinne des Vollbeweises nachgewiesen sei und die Schulterverletzung ueberwiegend degenerativ erklaerbar erscheine.")
add_h2(doc, "2. Gelegenheit zur Stellungnahme")
add_p(doc, "Dem Mandanten wird Gelegenheit gegeben, innerhalb von zwei Wochen ab Zugang zu den beabsichtigten Feststellungen Stellung zu nehmen und ergaenzende Beweismittel vorzulegen.")
add_h2(doc, "3. Stellungnahme der Kanzlei vom 10.06.2026")
add_p(doc, "Die Kanzlei verweist auf die Zeugenaussagen von Bastian Kopp und Sandra Lehnert, das Wartungsbuch mit mehrfachen Eintraegen zur Schwergaengigkeit der Rampe, den Kameraausfall im fraglichen Zeitraum sowie den intraoperativen Befund mit frischem Rupturrand. Es wird um Beruecksichtigung dieser Umstaende vor Erlass des Bescheids gebeten.")
add_h2(doc, "4. Ergebnis")
add_p(doc, "Die Berufsgenossenschaft erliess trotz der Stellungnahme am 18.06.2026 den Ablehnungsbescheid, ohne die vorgebrachten Gesichtspunkte nach Einschaetzung der Kanzlei angemessen zu wuerdigen.")
add_formathinweis(doc)
save(doc, BASE + "22_bg_anhoerung_vor_ablehnung.docx")

# 23 - BG-Ablehnungsbescheid komplett ausformuliert
doc = new_document()
add_title(doc, "Ablehnungsbescheid der Berufsgenossenschaft, ausformulierte Vollversion")
add_letterhead(doc, BG)
add_p(doc, "Datum: 18.06.2026")
add_h2(doc, "1. Bescheidtenor")
add_p(doc, "Die Anerkennung des Ereignisses vom 03.04.2026 als Arbeitsunfall wird abgelehnt. Ein Anspruch auf Leistungen der gesetzlichen Unfallversicherung, insbesondere Heilbehandlung, Verletztengeld und Verletztenrente, besteht nicht.")
add_h2(doc, "2. Sachverhalt")
add_p(doc, "Der Versicherte gibt an, am 03.04.2026 gegen 6:42 Uhr beim Loesen einer klemmenden Ueberladebruecke an Rampe 4 gestuerzt zu sein. Zeugen des unmittelbaren Sturzvorgangs liegen nicht vor. Die Videoaufzeichnung der betreffenden Kamera war im fraglichen Zeitraum unterbrochen.")
add_h2(doc, "3. Rechtliche Wuerdigung")
add_p(doc, "Nach Paragraf 8 Absatz 1 SGB VII ist Arbeitsunfall ein zeitlich begrenztes, von aussen auf den Koerper einwirkendes Ereignis, das zu einem Gesundheitsschaden fuehrt und das im Vollbeweis nachgewiesen sein muss. Die Berufsgenossenschaft sieht dieses Ereignis vorliegend nicht als hinreichend nachgewiesen an, da keine unmittelbare Beobachtung des Sturzvorgangs vorliegt und die medizinischen Befunde eine bereits vorbestehende degenerative Schaedigung der rechten Schulter zeigen.")
add_h2(doc, "4. Wuerdigung der medizinischen Befunde")
add_p(doc, "Der MRT-Befund vom 09.04.2026 zeige eine Teilruptur der Supraspinatussehne bei ausgepraegter AC-Gelenksarthrose. Die Berufsgenossenschaft geht davon aus, dass die Ruptur ueberwiegend wahrscheinlich auf dem vorbestehenden degenerativen Schaden beruht und lediglich zufaellig anlaesslich der beruflichen Taetigkeit symptomatisch geworden sei.")
add_h2(doc, "5. Nicht beruecksichtigte Gesichtspunkte")
add_p(doc, "Der Bescheid geht weder auf das Wartungsbuch der Rampe noch auf die uebereinstimmenden Erstangaben der Zeugen Kopp und Lehnert ein. Der Kameraausfall wird nur als technische Randnotiz erwaehnt, ohne beweisrechtliche Konsequenzen zu ziehen. Das intraoperativ dokumentierte Knochenmarkoedem wird nicht diskutiert.")
add_h2(doc, "6. Rechtsbehelfsbelehrung")
add_p(doc, "Gegen diesen Bescheid kann innerhalb eines Monats nach Zugang Widerspruch eingelegt werden. Der Bescheid gilt als am 22.06.2026 zugegangen; die Widerspruchsfrist endet damit am 22.07.2026.")
add_formathinweis(doc)
save(doc, BASE + "23_bg_ablehnungsbescheid_vollversion.docx")

print("Teil 4 fertig")
